config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'meetings#index'
  resources :meetings, only: [:index, :show]
  resources :users, only: [:show]

end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
# frozen_string_literal: true

# Meeting Model
class Meeting < ApplicationRecord
  has_many :records, dependent: :destroy
  has_many :users, -> { distinct }, through: :records, dependent: :destroy

  def contributions_by_number_of_participations
    contributions = {}
    users.each do |user|
      contributions[user.name] = user.number_of_participations_by_meeting(self)
    end
    contributions.sort_by { |_name, participations| -participations }
  end

  def contributions_by_avg_speak_time
    contributions = {}
    users.each do |user|
      contributions[user.name] = user.avg_speak_time(self)
    end
    contributions.sort_by { |_name, participations| -participations }
  end

  def contributions_by_total_speak_time
    contributions = {}
    users.each do |user|
      contributions[user.name] = user.total_speak_time(self)
    end
    contributions.sort_by { |_name, participations| participations }.reverse
  end

  def format_data
    recs = []
    records.each do |record|
      st = parse_time(record.start_date)
      et = parse_time(record.end_date)
      user = User.find_by_id(record.user_id).name

      recs << [user, et, st]
    end
    recs
  end

  private

  def parse_time(time)
    time.utc.strftime('%H:%M:%S')
  end
end

app/models/record.rb
# frozen_string_literal: true

# Record Model
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :meeting

  def self.sort_by_user_id
    order(user_id: :asc)
  end
end

app/models/user.rb
# frozen_string_literal: true

# User Model
class User < ApplicationRecord
  has_many :records
  has_many :meetings, -> { distinct }, through: :records

  def find_records_by_user
    records
  end

  def find_records_by_meeting(meeting)
    find_records(meeting)
  end

  def number_of_participations_by_meeting(meeting)
    find_records(meeting).count
  end

  def avg_speak_time(meeting)
    user_records = find_records(meeting)

    time_arr = user_records.map do |record|
      record.end_date - record.start_date
    end
    avg_time(time_arr)
  end

  def total_speak_time(meeting)
    user_records = find_records(meeting)

    time_arr = user_records.map do |record|
      record.end_date - record.start_date
    end
    total_time(time_arr)
  end

  private

  def avg_time(arr)
    avg_time_in_seconds = arr.inject(&:+) / arr.length.to_f
    convert_seconds_to_time(avg_time_in_seconds)
  end

  def total_time(arr)
    total_time_in_seconds = arr.inject(&:+)
    convert_seconds_to_time(total_time_in_seconds)
  end

  def convert_seconds_to_time(seconds)
    Time.at(seconds).utc.strftime('%H:%M:%S')
  end

  def find_records(meeting)
    records.where(meeting: meeting)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

# Meetings Controller
class MeetingsController < ApplicationController
  def index
    @meetings = Meeting.all
    render status: 404 if @meetings.nil?
  end

  def show
    @meeting = Meeting.find_by(id: params[:id])
    if @meeting.nil?
      redirect_to meetings_path, notice: 'Meeting Not Found'
    else
      @meeting_records = @meeting.format_data
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User Controller
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    redirect_to meetings_path, notice: 'User Not Found' if @user.nil?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# App Helper
module ApplicationHelper
end

app/helpers/meetings_helper.rb
# frozen_string_literal: true

# Meetings Helper
module MeetingsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# User Helper
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CombineAiChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-warning">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/meetings/index.html.erb
<div>
  <h1 class="text-center">Meetings</h1>
  <div class="alert alert-info" role="alert">
    click on a meeting to see it's records
  </div>
</div>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <th scope="row"><%= meeting.id %></th>
        <td><%=  link_to meeting.name, meeting_path(meeting.id)  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/meetings/show.html.erb
<div>
  <h1 class="text-center"><%= @meeting.name %></h1>
</div>
<div class="alert alert-info" role="alert">
    You can filter results by user name and click on the user to see it's data<br>
    Scroll down to see meeting stats
</div>
<br>
<table id="myTable" class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names..">
      <th scope="col">Start Time</th>
      <th scope="col">End Time</th>
    </tr>
  </thead>
  <tbody>
    <% @meeting_records.each do |record| %>
      <tr id="filterTable">
        <th scope="row"><%= link_to record[0], user_path(User.find_by_name(record[0]).id) %></th>
        <td><%= record[2] %></td>
        <td><%= record[1] %></td>
      </tr>
    <% end %>
  </tbody>
  <script>
    function myFunction() {
      // Declare variables
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("myInput");
      filter = input.value;
      table = document.getElementById("myTable");
      tr = table.getElementsByTagName("tr");

      // Loop through all table rows, and hide those who don't match the search query
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("th")[0];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }
  </script>
</table>

<br>
<h3> Participation Ranking </h3>
<table class="table table-hover">
  <tbody>
    <% participations = @meeting.contributions_by_number_of_participations %>
    <% participations.each do |user, value| %>
      <tr>
        <th scope="row"><%= user %></th>
        <td><%= value %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3> Average Speak Time Ranking </h3>
<table class="table table-hover">
  <tbody>
    <% participations = @meeting.contributions_by_avg_speak_time %>
    <% participations.each do |user, value| %>
      <tr>
        <th scope="row"><%= user %></th>
        <td><%= value %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3> Total Speak Time Ranking </h3>
<table class="table table-hover">
  <tbody>
    <% participations = @meeting.contributions_by_total_speak_time %>
    <% participations.each do |user, value| %>
      <tr>
        <th scope="row"><%= user %></th>
        <td><%= value %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<a class="btn btn-primary" href="#" role="button"><%= link_to "Return to Meetings", meetings_path%></a>

app/views/users/show.html.erb
<div>
  <h1 class="text-center"><%= @user.name %></h1>
</div>
<div class="alert alert-info" role="alert">
    You can check the meetings this user participate and it's state
</div>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Record</th>
      <th scope="col">Start Time</th>
      <th scope="col">End Time</th>
    </tr>
  </thead>
  <tbody>
    <% @user.records.each do |record| %>
      <tr>
        <% meeting = Meeting.find_by_id(record.meeting_id).name%>
        <th scope="row"><%= link_to meeting, meeting_path(record.meeting_id) %></th>
          <td><%=  record.start_date.strftime('%H:%M:%S')  %></td>
        <td><%=  record.end_date.strftime('%H:%M:%S')  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<div>
  <h2> Stats </h2>
</div>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Meeting</th>
      <th scope="col">Avg Speak Time</th>
      <th scope="col">Total Speak Time</th>
      <th scope="col">Participations</th>
      
    </tr>
  </thead>
  <tbody>
    <% @user.meetings.each do |meeting| %>
      <tr>
        <th scope="row"><%= link_to meeting.name, meeting_path(meeting.id) %></th>
        <td><%= @user.avg_speak_time(meeting) %></td>
        <td><%= @user.total_speak_time(meeting) %></td>
        <td><%= @user.number_of_participations_by_meeting(meeting) %></td>
      </tr>
    <% end %>
  </tbody>
</table>